name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GCP_SSH_KEY }}

      - name: Deploy to VM
        env:
          GCP_SSH_USER: ${{ secrets.GCP_SSH_USER }}
          GCP_SSH_HOST: ${{ secrets.GCP_SSH_HOST }}
        run: |
          echo "${{ secrets.GCP_SSH_KEY }}" > gcp_key
          chmod 600 gcp_key
          ssh -o StrictHostKeyChecking=no -i gcp_key $GCP_SSH_USER@$GCP_SSH_HOST << 'EOF'
            cd ~/onix/chatik
            git pull origin master
            docker-compose down
            docker-compose up -d --build
          EOF
